import os

BULWARK_PROTOCOL = os.getenv('BULWARK_PROTOCOL')
if not BULWARK_PROTOCOL:
    BULWARK_PROTOCOL = "https"
BULWARK_HOST = "localhost"
BULWARK_PORT = 1380
BULWARK_SECRET_KEY = "MyCoolSecretKey1234567890"
